# Generated by Django 3.0 on 2021-07-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
