# Generated by Django 3.0 on 2021-07-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_visit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case_paper_number',
            field=models.CharField(default='ANC-1', max_length=50),
            preserve_default=False,
        ),
    ]
