# Generated by Django 3.0 on 2021-07-26 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_case_paper_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='case_paper_number',
        ),
    ]
