# Generated by Django 3.0 on 2021-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilitysheet',
            name='intercourse_comment',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='fertilitysheet',
            name='ll_comment_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fertilitysheet',
            name='ll_comment_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fertilitysheet',
            name='ll_comment_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fertilitysheet',
            name='ll_comment_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fertilitysheet',
            name='physical_symptoms_comment',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
