# Generated by Django 3.0 on 2021-07-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210720_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g1_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g1_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g1_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g2_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g2_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g2_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g3_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g3_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g3_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g4_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g4_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g4_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g5_age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g5_comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='g5_sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
