# Generated by Django 3.0 on 2021-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20210720_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='gynacopdblock',
            name='scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gynacopdblock',
            name='scan_description',
            field=models.TextField(blank=True),
        ),
    ]
