# Generated by Django 3.0 on 2021-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20210720_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='g1',
            field=models.CharField(blank=True, choices=[('PTND', 'Ptnd'), ('FTND', 'Ftnd'), ('LSCS', 'Lscs'), ('IUD', 'Iud'), ('Missed Abortion', 'Missed Abortion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='g2',
            field=models.CharField(blank=True, choices=[('PTND', 'Ptnd'), ('FTND', 'Ftnd'), ('LSCS', 'Lscs'), ('IUD', 'Iud'), ('Missed Abortion', 'Missed Abortion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='g3',
            field=models.CharField(blank=True, choices=[('PTND', 'Ptnd'), ('FTND', 'Ftnd'), ('LSCS', 'Lscs'), ('IUD', 'Iud'), ('Missed Abortion', 'Missed Abortion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='g4',
            field=models.CharField(blank=True, choices=[('PTND', 'Ptnd'), ('FTND', 'Ftnd'), ('LSCS', 'Lscs'), ('IUD', 'Iud'), ('Missed Abortion', 'Missed Abortion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='g5',
            field=models.CharField(blank=True, choices=[('PTND', 'Ptnd'), ('FTND', 'Ftnd'), ('LSCS', 'Lscs'), ('IUD', 'Iud'), ('Missed Abortion', 'Missed Abortion')], max_length=20),
        ),
    ]
