# Generated by Django 3.0 on 2021-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20210720_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynacopdblock',
            name='date_added',
            field=models.DateField(),
        ),
    ]
