# Generated by Django 3.0 on 2021-07-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20210720_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancopdblock',
            name='date_added',
            field=models.DateField(),
        ),
    ]
