# Generated by Django 3.0 on 2021-07-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('records', '0009_auto_20210720_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfPlanTwoFirstBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('lmp', models.DateField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=15)),
                ('tablet_name', models.CharField(blank=True, max_length=150)),
                ('tablet_qty', models.CharField(blank=True, max_length=10)),
                ('tab_morning_qty', models.CharField(blank=True, max_length=10)),
                ('tab_afternoon_qty', models.CharField(blank=True, max_length=10)),
                ('tab_evening_qty', models.CharField(blank=True, max_length=10)),
                ('injection_name', models.CharField(blank=True, max_length=150)),
                ('injection_qty', models.CharField(blank=True, max_length=10)),
                ('day1', models.CharField(blank=True, max_length=50)),
                ('day2', models.CharField(blank=True, max_length=50)),
                ('day3', models.CharField(blank=True, max_length=50)),
                ('date1', models.DateField(blank=True, null=True)),
                ('date2', models.DateField(blank=True, null=True)),
                ('date3', models.DateField(blank=True, null=True)),
                ('flu_date', models.DateField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='InfPlanTwoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('right', models.CharField(blank=True, max_length=10)),
                ('left', models.CharField(blank=True, max_length=10)),
                ('et', models.CharField(blank=True, max_length=10)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('flu_date', models.DateField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='InfPlanOneFirstBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('lmp', models.DateField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=15)),
                ('tablet_name', models.CharField(blank=True, max_length=150)),
                ('tablet_qty', models.CharField(blank=True, max_length=10)),
                ('morning_qty', models.CharField(blank=True, max_length=10)),
                ('afternoon_qty', models.CharField(blank=True, max_length=10)),
                ('evening_qty', models.CharField(blank=True, max_length=10)),
                ('flu_date', models.DateField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='InfPlanOneBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField()),
                ('right', models.CharField(blank=True, max_length=10)),
                ('left', models.CharField(blank=True, max_length=10)),
                ('et', models.CharField(blank=True, max_length=10)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('flu_date', models.DateField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
