# Generated by Django 3.0 on 2021-07-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_infplanoneblock_infplanonefirstblock_infplantwoblock_infplantwofirstblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='date_added',
            new_name='date_added_a2',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='flu_date',
            new_name='flu_date_a2',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='date_added',
            new_name='date_added_a1',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='days',
            new_name='days_a',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='flu_date',
            new_name='flu_date_a1',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='lmp',
            new_name='lmp_a',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='date_added',
            new_name='date_added_b2',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='flu_date',
            new_name='flu_date_b2',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='date_added',
            new_name='date_added_b1',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='days',
            new_name='days_b',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='flu_date',
            new_name='flu_date_b1',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='lmp',
            new_name='lmp_b',
        ),
    ]
