# Generated by Django 3.0 on 2021-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20210721_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infplanonefirstblock',
            name='flu_date_a1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
