# Generated by Django 3.0 on 2021-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20210721_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='visit_no_a',
            new_name='visit_no',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='visit_no_b',
            new_name='visit_no',
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='visit_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gynacopdfirstblock',
            name='visit_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='infplanonefirstblock',
            name='visit_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='infplantwofirstblock',
            name='visit_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
