# Generated by Django 3.0 on 2021-07-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20210725_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='visit_no',
            new_name='visit_no_b',
        ),
        migrations.RenameField(
            model_name='ancopdfirstblock',
            old_name='visit_no',
            new_name='visit_no_a',
        ),
        migrations.RenameField(
            model_name='gynacopdblock',
            old_name='visit_no',
            new_name='visit_no_b',
        ),
        migrations.RenameField(
            model_name='gynacopdfirstblock',
            old_name='visit_no',
            new_name='visit_no_a',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='visit_no',
            new_name='visit_no_b',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='visit_no',
            new_name='visit_no_a',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='visit_no',
            new_name='visit_no_b',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='visit_no',
            new_name='visit_no_a',
        ),
    ]
