# Generated by Django 3.0 on 2021-07-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20210726_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='flu_date',
            new_name='flu_date_b',
        ),
        migrations.RenameField(
            model_name='gynacopdblock',
            old_name='flu_date',
            new_name='flu_date_b',
        ),
        migrations.AddField(
            model_name='ancopdfirstblock',
            name='flu_date_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gynacopdfirstblock',
            name='flu_date_a',
            field=models.DateField(blank=True, null=True),
        ),
    ]
