# Generated by Django 3.0 on 2021-07-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20210726_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='date_added',
            new_name='date_added_b',
        ),
        migrations.RenameField(
            model_name='ancopdfirstblock',
            old_name='date_added',
            new_name='date_added_a',
        ),
    ]
