# Generated by Django 3.0 on 2021-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20210726_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancopdfirstblock',
            name='date_added_a',
            field=models.DateField(),
        ),
    ]
