# Generated by Django 3.0 on 2021-07-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20210726_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancopdfirstblock',
            old_name='date_added_a',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='ancopdfirstblock',
            old_name='flu_date_a',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='ancopdfirstblock',
            old_name='visit_no_a',
            new_name='visit_no',
        ),
    ]
