# Generated by Django 3.0 on 2021-07-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20210727_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='date_added_b',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='flu_date_b',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='ancopdblock',
            old_name='visit_no_b',
            new_name='visit_no',
        ),
    ]
