# Generated by Django 3.0 on 2021-07-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_auto_20210727_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gynacopdblock',
            old_name='flu_date_b',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='gynacopdblock',
            old_name='visit_no_b',
            new_name='visit_no',
        ),
        migrations.RenameField(
            model_name='gynacopdfirstblock',
            old_name='flu_date_a',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='gynacopdfirstblock',
            old_name='visit_no_a',
            new_name='visit_no',
        ),
    ]
