# Generated by Django 3.0 on 2021-07-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_auto_20210728_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
