# Generated by Django 3.0 on 2021-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20210728_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gynacopdfirstblock',
            name='date_added',
            field=models.DateField(),
        ),
    ]
