# Generated by Django 3.0 on 2021-07-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_auto_20210728_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='comment_a',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='date_added_a2',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='et_a',
            new_name='et',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='flu_date_a2',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='left_a',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='right_a',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='infplanoneblock',
            old_name='visit_no_b',
            new_name='visit_no',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='date_added_a1',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='days_a',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='flu_date_a1',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='lmp_a',
            new_name='lmp',
        ),
        migrations.RenameField(
            model_name='infplanonefirstblock',
            old_name='visit_no_a',
            new_name='visit_no',
        ),
    ]
