# Generated by Django 3.0 on 2021-07-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_auto_20210729_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='comment_b',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='date_added_b2',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='et_b',
            new_name='et',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='flu_date_b2',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='left_b',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='right_b',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='infplantwoblock',
            old_name='visit_no_b',
            new_name='visit_no',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='date_added_b1',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='days_b',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='flu_date_b1',
            new_name='flu_date',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='lmp_b',
            new_name='lmp',
        ),
        migrations.RenameField(
            model_name='infplantwofirstblock',
            old_name='visit_no_a',
            new_name='visit_no',
        ),
    ]
