# Generated by Django 3.0 on 2021-07-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('records', '0026_auto_20210729_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='r1_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r1_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r2_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r2_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r3_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r3_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r4_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r4_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r5_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r5_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r6_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r6_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r7_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r7_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r8_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r8_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r9_check',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='r9_comment',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='tt1_date',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='tt2_date',
        ),
        migrations.AlterField(
            model_name='investigation',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
        migrations.CreateModel(
            name='Usg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1_check', models.BooleanField(default=False)),
                ('r2_check', models.BooleanField(default=False)),
                ('r3_check', models.BooleanField(default=False)),
                ('r4_check', models.BooleanField(default=False)),
                ('r5_check', models.BooleanField(default=False)),
                ('r6_check', models.BooleanField(default=False)),
                ('r7_check', models.BooleanField(default=False)),
                ('r8_check', models.BooleanField(default=False)),
                ('r9_check', models.BooleanField(default=False)),
                ('r1_comment', models.CharField(blank=True, max_length=50)),
                ('r2_comment', models.CharField(blank=True, max_length=50)),
                ('r3_comment', models.CharField(blank=True, max_length=50)),
                ('r4_comment', models.CharField(blank=True, max_length=50)),
                ('r5_comment', models.CharField(blank=True, max_length=50)),
                ('r6_comment', models.CharField(blank=True, max_length=50)),
                ('r7_comment', models.CharField(blank=True, max_length=50)),
                ('r8_comment', models.CharField(blank=True, max_length=50)),
                ('r9_comment', models.CharField(blank=True, max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='TtDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt1_date', models.DateField(blank=True, null=True)),
                ('tt2_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
